FROM mcr.microsoft.com/dotnet/core/sdk:3.1.404-alpine3.12 AS build-env
WORKDIR /app/build/

COPY M365.RoadMapInfo.sln **/*.csproj ./
RUN mkdir M365.RoadMapInfo       && mv M365.RoadMapInfo.csproj M365.RoadMapInfo/ && \
    dotnet restore -r linux-musl-x64
COPY . ./

RUN dotnet publish --no-restore -c Release -o /app/build/out -r linux-musl-x64 -f netcoreapp3.1 --self-contained=false

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic
WORKDIR /app
COPY --from=build-env /app/build/out/ .
ENTRYPOINT ["dotnet", "M365.RoadMapInfo.dll"]
