FROM alpine:latest AS build-env
WORKDIR /app/build/

RUN set -eux \
    & apk add \
        --no-cache \
        nodejs \
        yarn

COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install
COPY . ./
RUN mkdir ./public/features
RUN yarn export

FROM nginx:alpine
WORKDIR /app
COPY entrypoint.sh .
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN  chmod u+x entrypoint.sh
ENTRYPOINT /app/entrypoint.sh
EXPOSE 80
COPY --from=build-env /app/build/out/ /usr/share/nginx/html