FROM node:alpine
WORKDIR /app/build/

COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install
COPY . ./
RUN mkdir ./public/features
# ADD "https://m365roadmap-backend.mauricehessing.de/roadmap/data-hash" data-hash.json
RUN yarn build
CMD ["yarn", "start"]
EXPOSE 3000